on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    container: mpetienne/finistr2025:0.2
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Additional R packages
        run: |
          Rscript -e "install.packages(c('tictoc'))"
      - name: Generate slides
        run: "quarto render"
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #   steps:
  # 
  # build-deploy:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3
  # 
  #     - name: Set up Quarto
  #       uses: quarto-dev/quarto-actions/setup@v2
  # 
  #     - name: Render and Publish
  #       uses: quarto-dev/quarto-actions/publish@v2
  #       with:
  #         target: gh-pages
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}