on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build and Push Docker image"

jobs:
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    container: mpetienne/finistr2025:0.2
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Additional R packages
        run: |
          Rscript -e "install.packages(c('tictoc'))"
          Rscript -e "install.packages(c('animint2', 'data.table', 'dplyr', 'plyr', 'maps', 'terra', 'tidyr', 'lubridate'))"
          Rscript -e "install.packages(c('lubridate'))"
      - name: Generate slides
        run: "quarto render"
 